### ISSUE TITLE
DJ LEVELやクリアランプの表示

### ISSUE THREAD

**Issue by suitougreentea** [kenji0919/pirodx_manager#109]
# CLEAR LAMP
* プレーンテキスト
  * メリット…実装が一番単純 (既存のコードですぐ実現可能)
  * デメリット…飾り気がない
* テキスト+CSSによる装飾
  * メリット…実装が単純、外部リソース無し
  * デメリット…まだ何か物足りない
* 背景色のみ
  * メリット…外部リソースがいらない、分かる人には視覚的
  * デメリット…あまり目立たない、分からない人には分からない、アクセシビリティを考慮するならば不適
* 画像
  * メリット…公式で用いられている方法のため馴染みやすい
  * デメリット…画像の作成が必要

# DJ LEVEL
* プレーンテキスト
* テキスト+CSS装飾
* 画像

(メリット/デメリットはCLEAR LAMPと同様)

以上の案を組み合わせたり、新しい案があっても大歓迎です。

僕はプレーンテキスト+CSS派ですね。画像でもいいかも。

**Comment by kenji0919** [comment]
僕もとりあえずは、テキスト＋CSS装飾でやりたいですね。

いまの実装で、ユーザページに2曲だけは出るようになってるから（なってるよね？）、
そこをTable等で良い感じに表示できるように試してもらってもいいです？（依頼がざっくりしすぎだけど）

クリアランプとかの数値を文字列に戻す処理は、どうやるのがベストかよく分かっていないので、一旦無視して良いです。

**Comment by suitougreentea** [comment]
はい。試してみます。
