### ISSUE TITLE
ログの表示方法についての提案

### ISSUE THREAD

**Issue by suitougreentea** [kenji0919/pirodx_manager#132]
現在は、key(clear_lamp, score, miss_count)ごとに更新ログが登録されていますが、初プレイの時は3種類のログがまとめて追加されたり、一度にランプとスコアとBPが更新されることが多かったりで、ちょっと邪魔にならないかな、と思ったので、曲毎にログを追加するようにするのはどうでしょう？という提案です。
ついでに、メッセージは動的に生成される仕様でもいいかな、と考えています。
```
log = {
  iidx_id: String
  music_name: String
  type: String
  score_before: Integer or null
  score_after: Integer or null
  clear_lamp_before: Integer or null
  clear_lamp_after: Integer or null
  miss_count_before: Integer or null
  miss_count_after: Integer or null
  (score_my: Integer or null)
  (score_exceed: Boolean)
  (clear_lamp_my: Integer or null)
  (clear_lamp_exceed: Boolean)
  (miss_count_my: Integer or null)
  (miss_count_exceed: Boolean)
}
PirodxService.generate_log_message = (log) -> return hoge
```
(score, clear_lamp, miss_countは、更新がなかったらnull)

如何でしょうか？

**Comment by kenji0919** [comment]
> 曲毎にログを追加する

良いと思います。変更できるようであればしてみてください。（テスト直すのがちょっと面倒かも？）



> メッセージは動的

はい、こっちも薄々感じてはいました。Helperにでも、create_log()とかで移しておけばいいでしょうかね？

**Comment by kenji0919** [comment]
ちなみに、exceedはdefeatに改名しました。
もっと良い名前があったら、それを使ってもらって構いません。

**Comment by kenji0919** [comment]
このログの形式だと、リザルトが更新されたかはどうやって判断すれば良いだろうか？

スコアは更新したけど、ミスは更新できなかったときは、以下のようにmiss_countをnullにする？
```
score_before: old_score
score_after: new_score
miss_count_before: null
miss_count_after: null
```

どうせなら、更新できなかった時も全部保存すれば良いとも思うので、
update_score, update_miss_countなどのkeyを追加するのはいかがでしょうか？

**Comment by kenji0919** [comment]
## 要望
- 時間の情報をUTC秒で入れて頂けますか
- PirodxService.is_score_updated(log)などの関数が必要な気がするので、作って欲しい
  - PirodxLogを新しく作ってしまって、PirodxDB.create_logなども移すべき？

PirodxDBは、
- DBの初期化
- DBのリセット
- DBへのput, get
- Result, Music, Logを問わず、共通して利用できる便利関数

だけになるようにしたいです。（今はごちゃごちゃになっていて申し訳ありませんが）

**Comment by kenji0919** [comment]
多分これ、良いですよね。ありがとうございました。
