### ISSUE TITLE
update_music_dbの挙動

### ISSUE THREAD

**Issue by suitougreentea** [kenji0919/pirodx_manager#140]
現在の仕様では、曲データベースが存在している状態でupdateを行うと、変更の有無にかかわらずさらに曲が追加されてしまいます。

そこで代替策として、以下の2つの方法が思いつきますが、どうでしょうか？

* 一旦全削除して全て登録し直す
  * 結構時間がかかるので避けたほうが良い、という話だった気がします。
* DL後、共通部分、ローカルにしか無い曲、リモートにしか無い曲を検出する
  * 共通部分は1曲ごとに詳細情報を比較し、変更があったら登録しなおす
  * ローカルにしか無い曲は削除
  * リモートにしか無い曲は追加

**Comment by kenji0919** [comment]
全削除を避けた理由は、ローカルの編集が消えてしまうから、というのも大きかったような気がします。

以下のような感じでどうでしょう？
db_musicは先に書き換えちゃうことで、裏で時間がかかってもOKなようにしたいです。

- db_music_remoteをDL後、config['music_db_updated_at']より新しいデータなら以下の更新処理をする
- db_musicをdb_music_tmp等適当なサービス変数に退避し、db_music_remoteをdb_musicに代入
　- 見かけ上はすぐ使えるようになる（DBにはまだ反映されない）
- 退避したdb_musicを使って、差分を見て更新する（後者の方法）
- 全ての曲の更新が終わったら、config['music_db_updated_at']を更新する
  - 途中で画面更新などをしてしまった場合は、また最初からやり直せば問題ないはず

> 共通部分は1曲ごとに詳細情報を比較し、変更があったら登録しなおす

は、わざわざ詳細情報を比較しなくても、そのまま置き換えてDBに格納しても良い気がします。

**Comment by suitougreentea** [comment]
なるほど！そうしましょう。時間が取れたらPR作ります。
