### ISSUE TITLE
モバイルなUserAgentで正しくスクレイピングが行われない問題

### ISSUE THREAD

**Issue by suitougreentea** [kenji0919/pirodx_manager#149]

**Comment by kenji0919** [comment]
これは前々からそうだろうなぁ、と思っていましたが、
そもそもモバイルの細い回線でスクレイピングするものじゃないと思うので、
デスクトップでスクレイピング→サーバにデータ登録→モバイルはサーバからDLするだけ
という風にするのが良い気がします。

**Comment by suitougreentea** [comment]
なるほど。でしたらモバイルでは更新ボタンを無効にするなどの処理が必要でしょうかね。

**Comment by kenji0919** [comment]
はい、それがいいですね。
(サーバ対応できるかどうかは置いといて、)スクレイピング機能はモバイルでは非対応で良いと思います。

**Comment by suitougreentea** [comment]
はい。ありがとうございました!
