### ISSUE TITLE
各スクレイピングの進捗

### ISSUE THREAD

**Issue by suitougreentea** [kenji0919/pirodx_manager#55]
* [x] Follow
* [x] Follower
* [x] Music Info
* [x] Music List
* [x] My Best
* [x] Recent
* [x] Reverse Rival
* [x] Rival
* [x] Rival Challenge
* [x] Rival Search
* [x] Status
  * [x] My Result
  * [x] Rival

**Comment by kenji0919** [comment]
Statusページの、ライバル版がまだでしたね。

**Comment by kenji0919** [comment]
一通り終わったと思うので、Closeします。

今後は、
「PirodxService中で、各ページのURLに対してhttpリクエストを送り、
取得したページに対してデータを取得する。」
ということをやります。

その中で、ページクラスに対して追加したい機能が出てきたら、その都度PRを作りましょう。
