### ISSUE TITLE
サービスに必要な機能

### ISSUE THREAD

**Issue by kenji0919** [kenji0919/pirodx_manager#69]
欲しい機能と、それを実現するアルゴリズムを、できるだけ詳細に書いていきます。
おかしいところ、追記すべき項目・機能などは、コメントで議論しましょう。
関数名の案なども、自由に書いてOKです。

## 命名規則案
  - e-Amusementからデータを取得するものは、dl(downloadの意)というprefixをつける
  - ローカルのデータベースからデータを取得するものは、getというprefixをつける

## login_eam()
* [x] e-Amusementにログインする（ログインページに、POSTでID(またはe-mail), PASS, OTP(設定しなければ空文字)を送るだけで良い）
  * [x] Chrome Apps用には、Configページを作り、そこでID, PASS, OTPを設定し、localStorage(localForage)に保存する

## dl_user_info(iidx_id) # 自分のデータを取得する場合
* [x] user_infoを取得する
  * [x] ログイン後、statusページにアクセスし、pageからuser_infoを取得する
  * [ ] メンテナンス中はエラーを返す
  * [x] 取得したuser_infoをLocalStorageに保存する

## dl_user_info(iidx_id) # ライバルのデータを取得する場合
* [x] IIDX_IDを指定して、ユーザのデータを取得する
  * [x] IIDX_IDをパラメータにし、rival_searchページにアクセスしてtokenを取得する
  * [x] 取得したtokenを使用し、statusページにアクセスしてuser_infoを取得する

## dl_result(sp_dp, version=[0..21])
* [x] 自分の全リザルトを取得する
  * [x] バージョンを指定してmusic_listページにアクセス
  * [x] 最後のページまでめくり、最大のindexを取得する
  * [x] index = 0 ~ MAXまでのmusic_infoページに並列にアクセスしてスコアを取得し、マージする
  * [ ] 取得したデータをデータベースに記憶する
  * [ ] データベースに変更が生じたものを、バックエンドのサーバに送る
  * [ ] またその際、どのようにリザルト更新が更新されたかをLOGとして保存する

## dl_result_rival_all(sp_dp, versions, iidx_id)
* [x] 自分とライバルの全リザルトを取得する
  * [x] URLをライバル用の物に変え、自分のリザルトを取得する場合と同様の処理を行う
  * [x] 自分用のリザルトとライバル用のリザルトがあることに注意

## dl_result_quick(sp_dp, versions)
* [x] 自分の全リザルトを高速に取得する
  * [x] バージョンを指定して、music_listページにアクセスする
  * [x] ページ内のリザルトを取得する
  * [x] 最後のページになるまで、並列で上記を行い、マージする
  * [x] 1stから最新バージョンまで、並列で上記を行い、マージする

## dl_result_rival_quick(sp_dp, versions, iidx_id)
* [x] ライバルの全リザルトを高速に取得する
  * [x] URLをライバル用の物に変え、自分のリザルトを取得する場合と同様の処理を行う
  * [ ] ライバルのデータに変更があったら、ユーザにPush通知する

## dl_result_by_music_name(music_name, version)
* [x] 単曲のデータを名前から取得する
  * [ ] music_dbから、指定した曲名が所属するバージョンを求める
  * [x] 求めたバージョンを利用してmusic_listページにアクセスし、曲名を探す
  * [x] 曲名が見つかれば、indexを取得して、music_infoページにアクセスし、リザルトを取得する
  * [x] 曲名が見つからなければ、エラーを返す（PENDUALの隠し曲や、レジェンダリア等）

## dl_result_by_music_name(music_name, iidx_id)
* [x] URLをライバル用の物に変え、自分のリザルトを取得する場合と同様の処理を行う

## dl_rival_list()
* [ ] ライバル一覧を取得する
  * [ ] rivalページにアクセスし、ライバルのtoken一覧を取得する
  * [ ] 取得したtokenを利用し、statusページにアクセスしてuser_infoを取得する
  * [ ] user_infoをLocalStorageに保存する

## dl_reverse_rival_list()
* [ ] 逆ライバル一覧を取得する
  * [ ] ライバルと同様

## dl_follow_list()
* [ ] フォロー一覧を取得する
  * [ ] ライバルと同様

## dl_follower_list()
* [ ] フォロワー一覧を取得する
  * [ ] ライバルと同様

## dl_rival_challenge_list(iidx_id='all')
* [ ] 挑戦状一覧を取得する
  * [ ] rival_challengeページにアクセスし、挑戦状を取得する
  * [ ] LocalStorageに保存する
  * [ ] 挑戦状に更新があったら、ユーザにPush通知する

**Comment by kenji0919** [comment]
PirodxEAM.coffeeとPirodxDB.coffeeを作って、
- PirodxService.eam = PirodxEAM
- PirodxService.db = PirodxDB
みたいにして、関数を分割して管理したいので、良い感じにできそうか、確認してみます。

**Comment by kenji0919** [comment]
# リザルト
## put_result(result)
* [ ] @#{sp_dp}_resultにリザルトを保存する
  * [ ] minimongoへも同様の変更を適用する

## get_result([filter])
* [ ] @#{sp_dp}_resultからリザルトを取得する
  * [ ] filterとして、複数の条件を指定できる
  * [ ] 例えば、「spaのリザルト」かつ「曲のBPMが160～180」かつ「スコアの範囲がAまたはAA」などの条件

## push_result(result)
* [ ] リザルトをParseに保存する（要権限：自分のリザルトだけ保存できる）
  * [ ] 相手が許可してくれたら、相手のリザルトも代わりに保存できる

## pull_result([filter])
* [ ] リザルトをParseから取得する

# 曲データ
## put_music(music)
* [ ] @musicに曲データを保存する
  * [ ] minimongoへも同様の変更を適用する

## get_music([filter])
* [ ] @musicから曲データを取得する
  * [ ] filterとして、複数の条件を指定できる

## push_music(music)
* [ ] 曲データをParseに保存する（要管理者権限）
(この機能は、pirodx_musicdbで管理するかもしれない)

## pull_music([filter])
* [ ] 曲データをParseから取得する

# ユーザデータ
## put_user(user)
* [ ] @userにユーザデータを保存する
  * [ ] minimongoへも同様の変更を適用する

## get_user([filter])
* [ ] @userからユーザデータを取得する

## push_user(user)
* [ ] ユーザデータをParseに保存する（要権限：自分のリザルトだけ保存できる）

## pull_user([filter])
* [ ] ユーザデータをParseから取得する

**Comment by kenji0919** [comment]
LocalStorageはやめて、全てminimongoで管理した方が良いかなぁ、と思ったので、その方向で検討してみます。

サーバに保存する必要があるものだけ、選択してPushできるようなロジックをサービスに書きます。
また、不要なものを弾くロジックを、Parse（または代わりのバックエンド）に書きます。

**Comment by suitougreentea** [comment]
以上の案読みました。
* eAmからデータを取ってくるprefix、fetchでもいいかなーとか一瞬思ったのですが、dlで問題ないと思います
* check_login_eam: ネットワークに接続していない場合も考えると、返り値がbooleanじゃない方が良い？
  * 恐らく考えられる状態は、正常、非ログイン、メンテナンス、非接続、(サービス終了)
  * というか、スコアなどが正常に取得できる状態であるか、ってのを判別できるメソッドがあると良いかもしれません。(すべてstatusページから判別できると思います)
* dl_resultの、ログの内容
  * どのバージョンのどの曲が<旧リザルト>から<新リザルト>になった という情報を記録すれば良い？
* BPM絞り込みで、BPM変化がないとき、あるとき
  * ないとき: query.minbpm <= music.bpm <= query.maxbpm
  * あるとき: query.minbpm <= music.minbpm <= query.maxbpm || query.minbpm <= music.maxbpm <= query.maxbpm
  * でOKですか？
他にも何かあったら書き足します。

**Comment by suitougreentea** [comment]
* filterの書式
  * [{type: string, value: number, string, array, object (typeに依る)}, ...]
  * type = 'name', value: string
  * type = 'type', value: [string...] ('spn', 'sph', 'spa' / 'dpn', 'dph', 'dpa')
  * type = 'bpm', value: {min: number/string, max: number/string}
    * 現在BPMは内部ではstringで扱っていると思いますが、比較では結局数値にキャストすると思いますので、ちょっと迷ってます
  * type = 'clear_lamp', value: {min: number/string, max: number/string}
    * これも同上です。
  * type = 'dj_level', value: {min: number/string, max: number/string}
    * 同上です。
  * type = 'miss_count', value: {min: number/string, max: number/string}
    * 同上です。
  * type = 'play_count', value: {min: number/string, max: number/string}
    * 同上です。
他にも思いついたら足します。何か問題があれば指摘ください。

**Comment by kenji0919** [comment]
テストのmusic_db, result_dbを作って、
test_music_filter.coffee
test_result_filter.coffee
とかでテストしたいですね。

**Comment by kenji0919** [comment]
@suitougreentea さんには、Promise($q)の練習も兼ねて、
- music_listページにアクセス（SPのpendualバージョンのfixtureをmock）
- index=0を指定してmusic_infoページにアクセス(適当なリザルトのfixtureをmock。indexは正確に合っていなくて良い)
- music_infoページに対して、リザルトを取得
- リザルトが正しく取得できたかexpect

という流れのテストを書いてみてもらおうかな、と思っています。

ということで、今日～日曜日の間に、時間が合えばSkypeで相談しながらやってみましょう。

**Comment by kenji0919** [comment]
- filterの書式
内部の実装はどうするかまだ検討しなければいけませんが、
get_result([filter_list])等に与える引数としては、その形式が良さそうですね。
ただ、typeとして、['clear_lamp', 'score']等を指定するのではなくて、
filter_name: 'clear_lamp_betweeen', params: [0, 3] # 0~3を取得
filter_name: 'clear_lamp_match', params: [0, 4, 5] # 0, 4, 5だけ取得
のような形式にすると、柔軟なfilterが作れるのではないかと思いました。

実装案として、例えばこんな感じでしょうか。
get_result = ([filter_list]) ->
  for filter in filter_list
    ResultFilter.filter_function[filter.name](filter.params)

（詳細な実装については、別個でIssueを立てて、そこで議論するのが良いかな？）

**Comment by kenji0919** [comment]
しばらく更新が無いので閉じます。

何かあれば、個別にIssueを立てます。
