### ISSUE TITLE
then等のコールバックのカッコの付け方について

### ISSUE THREAD

**Issue by kenji0919** [kenji0919/pirodx_manager#87]
```
.then (data) ->
  ...
  ...
.catch (error) ->
  ...
```

にするか、

```
.then( (data) ->
  ...
  ...
).catch( (error) ->
  ...
)
```

にするか、どっちが良いと思いますか？
前者で、メソッドチェインしづらい場合があるんじゃないか、という心配があるので、
いつもなるべくカッコをつけるようにしてましたが、ムダに行数が増えるのがやだなぁ、と思っています。

**Comment by suitougreentea** [comment]
前者の書き方でチェインが正しく機能するなら、その方が見やすくていいと思います。
1行で書く場合 (`$(~).filter(-> ~~~).~~~`) は、括弧は(coffeescript的に)必須ですよね？

**Comment by kenji0919** [comment]
多分機能すると思います。

ただ、
①
```
$http.get().then () ->
  ...
  ...
.catch () ->
  ...
```

としてしまうと、動作したとしてもわかりにくいので、

②
```
$http.get()
.then () ->
  ...
  ...
.catch () ->
  ...
```

のようにしたいなぁ、と思っています。

以前カッコを付けていた理由には、①のように書いても、カッコの終わりでthenの終わりがすぐわかる、
という利点がありました。

**Comment by suitougreentea** [comment]
はい。賛成です。
メソッドチェーンでコールバックを引数に取る時には、②のような書き方にしましょう。

**Comment by kenji0919** [comment]
> 1行で書く場合 ($(~).filter(-> ~~~).~~~) は、括弧は(coffeescript的に)必須ですよね？

はい、真ん中のは必須だと思います。一番外のは要らないような？

**Comment by kenji0919** [comment]
それでは、見つけ次第直していく、ということで。
