### ISSUE TITLE
githubの活用法について

### ISSUE THREAD

**Issue by suitougreentea** [kenji0919/pirodx_manager#9]
色々考えてました。意見ください。
## Issueのラベル
* 元々あるラベル(bug, duplicate, enhancement, help wanted, invalid, question, wontfix)は有用だと思いますので残したいです
* Pull Requestの進捗に関するラベルがあると便利だと思います(2人なので、無くてもあまり変わらないかもしれません) (参考: http://www.publickey1.jp/blog/14/githubgithub_kaigi_2014_1.html)
  * ReviewRequire, ReviewProgress, ReviewFinished (名前はどうにでも)
* Issueの優先度
  * PriorityLow, PriorityMiddle, PriorityHighなど
* ラベルの種別でprefixを付けるとラベルの選択時にわかりやすいと思います
  * (例) priority_low, priority/low, PriorityLow

## Milestone
* Issueを紐付けることができる
* 開発の区切り(あるバージョンのリリースなど)までにどこまでのタスクを消化したいかを決められる
* 期限も決められる(あまり使わなそう)
* 個人的には進捗が視覚的になるので面白い機能だと思います

**Comment by suitougreentea** [comment]
work_in_progressラベルを追加してみました。
PRで、まだマージしてはいけない作業中のものに付ける想定です。

**Comment by kenji0919** [comment]
なんとなく使い方が決まってきた気がするので、一旦閉じときますね。
必要ならまた開いて下さい。
