### ISSUE TITLE
gulp-concatの導入

### ISSUE THREAD

**Issue by kenji0919** [kenji0919/pirodx_manager#95]
https://github.com/kenji0919/pirodx_manager/blob/master/app/scripts/service/PirodxService.coffee#L5
でやっているようなことって、concatでやった方がスマートだなぁ、と思いました（これのやり方がわからなかったので、仕方なく黒魔術的なファイル結合をしていました。）

また、リリース時にはminifyも試してみたいですね。（ローカルファイルなのであまり意味が無いと思いますが）

【参考】
http://dev.classmethod.jp/client-side/javascript/gulp-js-task-files/

**Comment by kenji0919** [comment]
単純に複数ファイルを結合するのだと、module.exportsの部分の処理が難しそうなのでちょっと考えています。

**Comment by kenji0919** [comment]
#96 でやってみましたが、綺麗に書けそうもなかったので諦めました（結局黒魔術をつかった）

参考までに、一応アレでテストは通りました

**Comment by kenji0919** [comment]
確認してくれたら閉じます。

**Comment by suitougreentea** [comment]
はい。Closeします。
